<?php
  snippet('global.head');
  snippet('global.menu');
  snippet('global.header');
  snippet('global.textblock');
  snippet('global.sidebar');
  snippet('global.cta');
  snippet('global.footer');
?>